Ygoproco/Live2017MR4

script/c70238111.lua

Another script issue with my server. Fix by AlphaKretin, uploading for him.

Fix Recoded Alive

---

script/c92781606.lua

Fix setcode

---

script/c100305031.lua

small error fix

---

script/c54658815.lua

anomaly on when selecting zones to spsummon.

small bug fix

---

script/c511004408.lua

updated string description and token id (database not included)

update to predator gemination

---

script/utility.lua

targetboolfunction (aparenty istype/attribute/... don't accept nil, making that until it looked on core)

provisory fix

---

script/utility.lua

added a nil checker

---

script/utility.lua

reverting it again

---

script/c101003059.lua

https://github.com/Fluorohydride/ygopro-pre-script/blob/master/scripts/EXFO-JP/c101003059.lua

small fix (nekrozar)

---

script/c2095764.lua
script/c30106950.lua
script/c35089369.lua
script/c37675907.lua
script/c39964797.lua
script/c50091196.lua
script/c575512.lua
script/c62899696.lua
script/c66500065.lua
script/c70939418.lua
script/c71386411.lua
script/c83295594.lua
script/c85704698.lua
script/c98558751.lua
script/c99946920.lua

prevents Synchro Summoning face-down cards

Synchro Summoning fix

---

script/c93503294.lua

Altergeist Prime Banshee was using beta setcode

Updated setcode check for Altergeist Prime Banshee

---

script/c26285788.lua
script/c76224717.lua

Material should only count monsters

Advance Zone + Trial and Tribulation fix

---

script/c97795930.lua

multiple copies should not stack

Phantasm Spiral Assault fix

---

script/c14558127.lua

Effect can only be applied if affected card is not yet negated by another effect

Ash Blossom & Joyous Springs fix

---

script/c30539496.lua
script/c82321037.lua
script/c96746083.lua

Should allow activation if assured to destroy on the field

True Kings fix vs My Body as a Shield

---

script/c22802010.lua

Only allows chaining if there are Level 1/Rank 1 monsters

Blind Obliteration vs My Body as a Shield fix

---

script/c16762927.lua
script/c170000170.lua
script/c21417692.lua
script/c37869028.lua
script/c38369349.lua
script/c42035044.lua
script/c42035045.lua
script/c511001131.lua
script/c511003013.lua
script/c511003014.lua
script/c511003015.lua
script/c511003017.lua
script/c511015116.lua
script/c53183600.lua
script/c58054262.lua
script/c59560831.lua
script/c65458948.lua
script/c82003859.lua
script/c82199284.lua
script/c91512835.lua
script/c91842653.lua

Fixes for cards that check EFFECT_ATTACK_COST

---

lflist.conf

Updated: TCG, OCG, Worlds, Traditional and Anime

Update for F/L lists

---

script/c101003052.lua

changed order, and added a check for nil variable.

smoll fix for fire prison

---

script/c32013448.lua

Now points to correct string (added in fixstr.cdb)

Fix for description given to Ritual monsters

---

script/c6628343.lua

Now points to the correct string (added in fixstr,cdb)

Fixed description given to a Ritual Monster

---

script/c101003039.lua

wrong bool function and using outdated function.

fix for Underclock Taker

---

script/c101003100.lua

small fix for Electronic Transimulation Wattkinesis

---

script/c99427357.lua

fix for サイバー・エンジェル－那沙帝弥－ (cyber angel natasha)

---

script/c101003019.lua

related with https://github.com/Ygoproco/Live2017MR4/pull/108

update condition check in Jack Knight of the Azure Blue

---

script/c14318794.lua

Multiple copies should be cumulative

Life Absorbing Machine fix

---

script/c6172122.lua

Red-Eyes Fusion vs Ash Blossom

---

script/c100407008.lua

fix for queen

---

script/c100000246.lua

updated alchemical experiment

---

script/c101003031.lua

return effect thing
related with:
https://github.com/Ygoproco/Live2017/pull/589

fix for D.D porsuit

---

script/c16306932.lua

fix for special summon proc (used from percy)

odd-eyes revolution dragon

---

script/c100407002.lua

fix for facelless mage

---

script/c37433748.lua

Only possible for "next update"

SPYRAL - Last Resort cleanup

---

script/c86937530.lua

Ash Blossom & Joyous Spring can be chained to Luna's 2nd effect

Fairy Tail - Luna fix

---

script/c101003052.lua

https://github.com/Fluorohydride/ygopro-pre-script/blob/master/scripts/EXFO-JP/c101003052.lua

Fixed Fire Prison

---

script/c101003038.lua

Fixed Excode Talker

---

script/proc_link.lua

fix for link prochedure

---

script/c101003053.lua
script/proc_pendulum.lua
script/proc_ritual.lua

Double checked, nothing changed but description

Even better description

---

script/c101002086.lua
script/c101003050.lua

Outdated function in Link procedure

Small Fixes

---

script/c101003064.lua

cleanup and problem on not abble to select zones, also simplified sequence conversion

fix for asport

---

script/c51562916.lua

Added check for Blue-Eyes Spirit Dragon

Big Wave Small Wave fix

---

script/c101003027.lua

small fix for Mythical Beast Master Cerberus

---

script/c14745409.lua
script/c24668830.lua
script/c83225447.lua

Noble Arms Galattin
Stim-Pack
Infection Germ

Fix for Equip Spells that change stat over time

---

script/utility.lua

Number shown as hint to view how many are needed to be selected

SelectUnselect Number Hint

---

script/c28570310.lua

credit to https://github.com/Ygoproco/Live2017MR4/pull/185
(can close that PR refered)

fix for Mythical Beast Garuda

---

script/c32391631.lua
script/c70902743.lua

If the attack was negated, monsters would not be destroyed by End Phase effect

Savage Colloseum/Red Dragon Archfiend ruling

---

script/c100223031.lua

small fix for hieratic seal

---

script/c100223006.lua

specialsummon step --credit to alpha

Fix "Gladiator Beast Dragacius"

---

script/c2144946.lua
script/c75059201.lua

small fix (wrong name/typo)

---

script/c8310162.lua

small fix (old prochedure case)

---

script/c100223091.lua

undefined tc, also wrong amount.

small fix for cryston habifer

---

script/c32472237.lua

small fix for Metalrokket Dragon

---

script/c27354732.lua

fix for 27354732

---

script/c74997493.lua

error fix for 74997493

---

script/c16719140.lua

Prevent trigger if attack is negated

 Subterror Nemesis Warrior fix

---

script/c100407008.lua

small fix for ultimate insect idk

---

lflist.conf
script/c94388754.lua

Includes changes to TCG and changes in Worlds and Traditional to match the TCG changes.

Update for mutiples F/L Lists
